ProjectTracker/ProjectTracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('projects.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
]

ProjectTracker/projects/urls.py
from django.urls import path

from . import views

app_name="projects"
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('projects/<slug:slug>/', views.project_detail, name='project_detail'),
    path('projects/<slug:slug>/delete', views.delete_project, name='delete_project'),
]

ProjectTracker/oauth/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass

ProjectTracker/projects/models.py
from django.utils import timezone 
from django.conf import settings
from django.core.validators import ValidationError, MaxLengthValidator
from django.forms import ModelForm
from django.db import models
from oauth.models import User
# Create your models here.

class Project(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=60, validators=[MaxLengthValidator(60)])
    slug = models.SlugField(max_length=120, validators=[MaxLengthValidator(120)])
    total_time = models.PositiveIntegerField(default=0)
    last_worked_on = models.DateTimeField(default=timezone.now)

    def clean(self):
        if (Project.objects.filter(owner=self.owner, title=self.title)):
            raise ValidationError('Title must be unique')

class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['title',]
    
class Session(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    total_time = models.PositiveIntegerField(default=0)

    def clean(self):
        if self.start_date > self.end_date:
            raise ValidationError('Start date is after end date')
        
class SessionForm(ModelForm):
    class Meta:
        model = Session
        fields = ['start_date', 'end_date', 'total_time',]

class Milestone(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    date = models.DateTimeField()
    description = models.CharField(max_length=200, validators=[MaxLengthValidator(200)])

class MilestoneForm(ModelForm):
    class Meta:
        model = Milestone
        fields = ['date', 'description',]

    
     

    

ProjectTracker/oauth/views.py
from django.shortcuts import render

# Create your views here.

ProjectTracker/projects/views.py
import re
from time import time
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from slugify import slugify

from projects.models import Project, ProjectForm, Session, SessionForm, Milestone, MilestoneForm

# Create your views here.

def dashboard(request):
    if not request.user.is_authenticated:
        return render(request, 'projects/dashboard_noauth.html')

    if request.method == 'POST':
        project = Project(owner=request.user)
        formset = ProjectForm(request.POST, instance=project)
        if formset.is_valid():
            new_project = formset.save(commit=False)
            new_project.slug = slugify(project.title)
            formset.save()
    else:
        formset = ProjectForm()

    projects = Project.objects.filter(owner=request.user)
    return render(request, 'projects/dashboard.html', {'projects' : projects, 'formset' : formset})

def project_detail(request, slug):
    project = Project.objects.filter(owner=request.user).get(slug=slug)
    sessions = Session.objects.filter(project=project)
    milestones = Milestone.objects.filter(project=project)

    if request.method == 'POST':
        if request.POST['type'] == 'session':
            session = Session(project=project)
            formset = SessionForm(request.POST, instance=session)
            project.last_worked_on=request.POST['end_date']
            project.total_time += int(request.POST['total_time'])
            if formset.is_valid():
                formset.save()
                project.save()
        elif request.POST['type'] == 'milestone':
            milestone = Milestone(project=project)
            formset = MilestoneForm(request.POST, instance=milestone)
            if formset.is_valid():
                formset.save()
            
    return render(request, 'projects/project_detail.html', {'project' : project, 'sessions' : sessions, 'milestones' : milestones})


def delete_project(request, slug):
    Project.objects.filter(owner=request.user).get(slug=slug).delete()
    return redirect("/");

ProjectTracker/projects/templates/projects/dashboard.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Projects</title>
        {% load static%}
        {% load project_filters %}
        <link rel="stylesheet" href="{% static 'projects/dashboard.css' %}">
        <link rel="stylesheet" href="{% static 'projects/table.css' %}">
        <link rel="stylesheet" href="{% static 'projects/button.css' %}">
    </head>
    <body>
        {% include "projects/nav.html" %}
        <button type="button" class="primary-button table-aligned" id="new-project-button">New Project</button>
        <table>
            <tr>
                <th>Project</th>
                <th>Time</th>
                <th colspan=2>Last Worked On</th>
            </tr>
            <tr id="new-project-row" hidden>
                <td colspan=4>
                    <form method="post"> 
                        {% csrf_token %}
                        <input type="text" id="title" name="title" placeholder="Project Name">
                        <input class="primary-button" type="submit" value="Submit">
                    </form>
                </td>
            </tr>
            {% for project in projects %}
            <tr>
                <td><a href={% url 'projects:project_detail' project.slug %}>{{project.title}}</a></td>
                <td>{{project.total_time|seconds_to_time}}</td>
                <td>{{project.last_worked_on}}</td>
                <td>
                    <div class="kebab" id="project-kebab">
                        <figure></figure>
                        <figure class="middle"></figure>
                        <p class="cross">x</p>
                        <figure></figure>
                        <ul class="dropdown">
                            <li><a href={% url 'projects:delete_project' project.slug %}>Delete</a></li>
                        </ul>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </table>

        <script>
            document.getElementById("new-project-button").onclick = new_project;
            function new_project() {
                document.getElementById("new-project-row").hidden = false;
                document.getElementById("title").focus();
            }

            const kebabs = document.getElementsByClassName("kebab");
            for (let i = 0; i < kebabs.length; i++) {
                kebabs[i].addEventListener('click', function() {
                    kebabs[i].querySelector('.dropdown').classList.toggle('active');
                    kebabs[i].querySelector('.cross').classList.toggle('active');
                    kebabs[i].querySelector('.middle').classList.toggle('active');
                })
            }
        </script>
    </body>
</html> 

ProjectTracker/projects/templates/projects/dashboard_noauth.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Projects</title>
    </head>
    <body>
        {% include "projects/nav.html" %}
    </body>
</html> 

ProjectTracker/projects/templates/projects/nav.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <link rel="stylesheet" href="{% static 'projects/nav.css' %}">
        <link rel="stylesheet" href="{% static 'projects/reset.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet"> 
    </head>
    <body>
        <div class="nav-container">
            <a href=/>Dashboard</a>
            <div class="nav-spacer"></div>
            {% if user.is_authenticated %}
              <a href="/accounts/logout">Logout</a>
            {% else %}
              <a href="/accounts/login">Login</a>
            {% endif %}
        </div>
    </body>
</html>

ProjectTracker/projects/templates/projects/project_detail.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Projects</title>
        {% load static %}
        {% load project_filters%}
        <script src="{% static 'projects/project_detail.js' %}"></script> 
        <link rel="stylesheet" href="{% static 'projects/button.css' %}">
        <link rel="stylesheet" href="{% static 'projects/table.css' %}">
        <link rel="stylesheet" href="{% static 'projects/timer.css' %}">
    </head>
    <body>
        {% include "projects/nav.html" %}
        <div class="timer">
            <p class="timer-time"><span id="hours">00</span>:<span id="minutes">00</span>:<span id="seconds">00</span></p>
            <div class="timer-controls">
                <button class="primary-button" id="button-start">Start</button>
                <button class="primary-button" id="button-end">End</button>
                <button hidden id="button-reset">Reset</button>
            </div>
        </div>

        <form id="session-form" method="POST">    
            {% csrf_token %}
            <input type="hidden" id="start_time" name="start_date"></input>
            <input type="hidden" id="end_time" name="end_date"></input>
            <input type="hidden" id="total_time" name="total_time"></input>
            <input type="hidden" id="type" name="type" value="session"></input>
        </form>

        <form id="milestone-form" method="POST">    
            {% csrf_token %}
            <input type="hidden" id="milestone-description" name="description"></input>
            <input type="hidden" id="milestone-date" name="date"></input>
            <input type="hidden" id="milestone-type" name="type" value="milestone"></input>
            <button hidden type="hidden" id="milestone-submit" name="milestone-submit">Save Milestone</button>
        </form>

        <table>
            <tr>
                <th>Start</th>
                <th>End</th>
                <th>Time</th>
            </tr>
            {% for session in sessions %}
            <tr>
                <td>{{session.start_date|date:'m-d-Y h:i a'}}</a></td>
                <td>{{session.end_date|date:'m-d-Y h:i a'}}</td>
                <td>{{session.total_time|seconds_to_time}}</td>
            </tr>
            {% endfor %}
        </table>

        {% comment %} <table>
            <tr>
                <th>Date</th>
                <th>Description</th>
            </tr>
            {% for milestone in milestones %}
            <tr>
                <td>{{milestone.date|date:'m-d-Y h:i a'}}</a></td>
                <td>{{milestone.description}}</td>
            </tr>
            {% endfor %}
        </table> {% endcomment %}
    </body>
</html> 